#!/usr/bin/env php
<?php

if (file_exists('./vendor/autoload.php')) {
    require './vendor/autoload.php';
} else if(file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../../bootstrap/autoload.php';
}

if (file_exists('./bootstrap/app.php')) {
    $app = require'./bootstrap/app.php';
} else {
    $app = require __DIR__.'/../../../bootstrap/app.php';
}


$kernel = $app->make(INTCore\OneARTConsole\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

/*
|--------------------------------------------------------------------------
| Shutdown The Application
|--------------------------------------------------------------------------
|
| Once Artisan has finished running, we will fire off the shutdown events
| so that any final work may be done by the application before we shut
| down the process. This is the last thing to happen to the request.
|
*/

$kernel->terminate($input, $status);

exit($status);
